export const PERMISSIONS = {
  STAFF_READ_ALL: "STAFF_READ_ALL",
  CUSTOMER_READ_ALL: "CUSTOMER_READ_ALL",
  USER_UPDATE_ANY: "USER_UPDATE_ANY",
  USER_READ_STATS: "USER_READ_STATS",
  STAFF_ASSIGN_ROLE: "STAFF_ASSIGN_ROLE",
  PERMISSION_DELEGATE: "PERMISSION_DELEGATE",
  RECEIVE_NEW_CASE: "RECEIVE_NEW_CASE",
  ACCESS_USER_DETAIL: "ACCESS_USER_DETAIL",

  CASE_READ_ALL: "CASE_READ_ALL",
  CASE_READ_HIERARCHY: "CASE_READ_HIERARCHY",
  CASE_ASSIGN: "CASE_ASSIGN",
  CASE_SET_PRIORITY: "CASE_SET_PRIORITY",
  CASE_READ_ANALYTICS: "CASE_READ_ANALYTICS",
  CASE_READ_OWN_ANALYTICS: "CASE_READ_OWN_ANALYTICS",
  CASE_CREATE: "CASE_CREATE",
  VIEW_ALL_CASES_METRICS: "VIEW_ALL_CASES_METRICS",
  VIEW_ALL_CASES_DETAIL: "VIEW_ALL_CASES_DETAIL",

  STRUCTURE_MANAGE: "STRUCTURE_MANAGE",
  STRUCTURE_READ_ALL: "STRUCTURE_READ_ALL",
  STRUCTURE_READ_OWN: "STRUCTURE_READ_OWN",

  SERVICE_MANAGE: "SERVICE_MANAGE",
  ORGANIZATION_MANAGE: "ORGANIZATION_MANAGE",

  PRODUCT_MANAGE: "PRODUCT_MANAGE",
  PRODUCT_READ_ALL: "PRODUCT_READ_ALL",
} as const;

export const LEGACY_PERMISSION_ALIASES: Record<string, string> = {
  CASE_READ_OWN_ANALTICS: PERMISSIONS.CASE_READ_OWN_ANALYTICS,
};

export const normalizePermissionCode = (code?: string | { code?: string } | null): string => {
  if (!code) return "";

  const rawValue = typeof code === "string"
    ? code
    : typeof code === "object" && "code" in code && typeof code.code === "string"
      ? code.code
      : "";

  const raw = rawValue.trim().toUpperCase();
  if (!raw) return "";
  return LEGACY_PERMISSION_ALIASES[raw] || raw;
};

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  SYSTEM_ADMIN: [
    PERMISSIONS.STAFF_READ_ALL,
    PERMISSIONS.CUSTOMER_READ_ALL,
    PERMISSIONS.USER_UPDATE_ANY,
    PERMISSIONS.USER_READ_STATS,
    PERMISSIONS.CASE_READ_ALL,
    PERMISSIONS.CASE_READ_HIERARCHY,
    PERMISSIONS.CASE_ASSIGN,
    PERMISSIONS.CASE_SET_PRIORITY,
    PERMISSIONS.CASE_READ_ANALYTICS,
    PERMISSIONS.STRUCTURE_MANAGE,
    PERMISSIONS.STRUCTURE_READ_ALL,
    PERMISSIONS.SERVICE_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.PERMISSION_DELEGATE,
    PERMISSIONS.CASE_CREATE,
    PERMISSIONS.VIEW_ALL_CASES_METRICS,
    PERMISSIONS.VIEW_ALL_CASES_DETAIL,
    PERMISSIONS.RECEIVE_NEW_CASE,
    PERMISSIONS.ACCESS_USER_DETAIL,
  ],

  DIRECTOR: [
    PERMISSIONS.USER_READ_STATS,
    PERMISSIONS.CASE_READ_ALL,
    PERMISSIONS.CASE_READ_ANALYTICS,
    PERMISSIONS.STRUCTURE_READ_ALL,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.VIEW_ALL_CASES_METRICS,
    PERMISSIONS.VIEW_ALL_CASES_DETAIL,
  ],

  MANAGER_DEPARTMENT: [
    PERMISSIONS.STRUCTURE_READ_OWN,
    PERMISSIONS.USER_READ_STATS,
    PERMISSIONS.CASE_READ_HIERARCHY,
    PERMISSIONS.CASE_ASSIGN,
    PERMISSIONS.CASE_SET_PRIORITY,
    PERMISSIONS.CASE_READ_OWN_ANALYTICS,
  ],
  MANAGER_DIVISION: [
    PERMISSIONS.STRUCTURE_READ_OWN,
    PERMISSIONS.USER_READ_STATS,
    PERMISSIONS.CASE_READ_HIERARCHY,
    PERMISSIONS.CASE_ASSIGN,
    PERMISSIONS.CASE_SET_PRIORITY,
    PERMISSIONS.CASE_READ_OWN_ANALYTICS,
  ],
  MANAGER_SECTION: [
    PERMISSIONS.STRUCTURE_READ_OWN,
    PERMISSIONS.STAFF_READ_ALL,
    PERMISSIONS.USER_READ_STATS,
    PERMISSIONS.CASE_READ_HIERARCHY,
    PERMISSIONS.CASE_ASSIGN,
    PERMISSIONS.CASE_SET_PRIORITY,
    PERMISSIONS.CASE_READ_OWN_ANALYTICS,
  ],
  PS_SUPPORT: [
    PERMISSIONS.STRUCTURE_READ_OWN,
    PERMISSIONS.CASE_READ_HIERARCHY,
    PERMISSIONS.CASE_READ_OWN_ANALYTICS,
  ],
};

export const getDefaultPermissionCodes = (role?: string, managerType?: string): string[] => {
  if (!role) return [];

  const normalizedRole = role.trim().toUpperCase();

  const baseCodes =
    normalizedRole === "MANAGER"
      ? managerType
        ? DEFAULT_ROLE_PERMISSIONS[`MANAGER_${managerType.trim().toUpperCase()}`] ?? []
        : []
      : DEFAULT_ROLE_PERMISSIONS[normalizedRole] ?? [];

  return baseCodes.map((code) => normalizePermissionCode(code));
};

export const getEffectivePermissionCodes = (
  role?: string,
  managerType?: string,
  extraCodes: string[] = []
): string[] => {
  const defaultCodes = getDefaultPermissionCodes(role, managerType);
  const normalizedExtra = (extraCodes || [])
    .map((code) => normalizePermissionCode(code))
    .filter(Boolean);

  return Array.from(new Set([...defaultCodes, ...normalizedExtra]));
};
